# workflow that builds and tests the cpp-devcontainer

name: linux dev image
on:
  schedule:
    - cron: "25 16 * * *"
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

env:
  IMAGE_FILE: "linux-dev.Dockerfile"

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: "actions/checkout@v3"

      - name: Docker build
        shell: pwsh
        working-directory: cpp
        run: >
          docker build
          --file ${{ env.IMAGE_FILE }}
          --tag ${{ env.IMAGE_TAG }}
          .

